project:
  type: website

website:
  title: "ISSS608 VAA üé®"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 0"
            href: Hands-on_Ex/Hands-on_Ex00.html
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01.html
          - text: "Hands-on Exercise 2"
            href: Hands-on_Ex/Hands-on_Ex02.html            
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: "https://public.tableau.com/app/profile/sindy.hua/viz/In-class_Ex01_17371867037820/Dashboard1"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: Take-home_Ex1.html
    right:
      - href: index.qmd
        text: "üöÄ Home"
      - href: about.qmd
        text: "üí°Ô∏è About"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    # Optional: Uncomment if using custom JS
    # js: scripts.js

editor: visual
